import type { Preview } from '@storybook/nextjs-vite'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { initialize, mswLoader } from 'msw-storybook-addon'
import React from 'react'

import { Toaster } from '../components/ui/sonner'
import { NotificationsListener } from '../app/notifications-listener'
import '../app/globals.css'

// Initialize MSW once for the whole Storybook session. The service worker
// lives at /mockServiceWorker.js (generated by `npx msw init public/`).
initialize({ onUnhandledRequest: 'bypass' })

const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    a11y: { test: 'todo' },
  },
  loaders: [mswLoader],
  decorators: [
    (Story) => {
      // Fresh QueryClient per story so cache state never leaks.
      const client = new QueryClient({
        defaultOptions: {
          queries: { retry: false, staleTime: 60_000, refetchOnWindowFocus: false },
          mutations: { retry: false },
        },
      })
      return (
        <QueryClientProvider client={client}>
          <Story />
          <NotificationsListener />
          <Toaster />
        </QueryClientProvider>
      )
    },
  ],
}

export default preview
